services:
  apigateway:
    build: ./backend/api_gateway/
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - todoservice

  todoservice:
    build: ./backend/todo_service/
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    ports:
      - 8001:8001
    depends_on:
      - mysql

  mysql:
    build: ./backend/todo_db/
    restart: always
    ports:
      - '3306:3306'

  react-todo-app:
    depends_on:
      - apigateway
    build:
      context: ./frontend/todo-app/
    ports:
      - "3000:3000"
    container_name: react-todo-app
    stdin_open: true
    volumes:
       - ./todo-app:/usr/src/app/todo-app
       - /usr/src/app/todo-app/node_modules